"""Initial standalone ADS HRM schema"""
from alembic import op
import sqlalchemy as sa
revision="0001"; down_revision=None; branch_labels=None; depends_on=None
def upgrade():
    op.create_table("hrm_users",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("email",sa.String(190),nullable=False),sa.Column("password_hash",sa.String(255),nullable=False),sa.Column("is_active",sa.Boolean(),nullable=False),sa.Column("created_at",sa.DateTime(),nullable=False)); op.create_index("ix_hrm_users_email","hrm_users",["email"],unique=True)
    op.create_table("hrm_employees",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("employee_code",sa.String(30),nullable=False),sa.Column("full_name",sa.String(150),nullable=False),sa.Column("email",sa.String(150)),sa.Column("phone",sa.String(30)),sa.Column("department",sa.String(100),nullable=False),sa.Column("designation",sa.String(100),nullable=False),sa.Column("employment_type",sa.String(30),nullable=False),sa.Column("join_date",sa.Date(),nullable=False),sa.Column("basic_salary",sa.Numeric(12,2),nullable=False),sa.Column("emergency_contact",sa.String(100)),sa.Column("address",sa.Text()),sa.Column("is_active",sa.Boolean(),nullable=False),sa.Column("created_at",sa.DateTime(),nullable=False)); op.create_index("ix_hrm_employees_employee_code","hrm_employees",["employee_code"],unique=True); op.create_index("ix_hrm_employees_full_name","hrm_employees",["full_name"])
    op.create_table("hrm_attendance",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("employee_id",sa.Integer(),sa.ForeignKey("hrm_employees.id"),nullable=False),sa.Column("attendance_date",sa.Date(),nullable=False),sa.Column("status",sa.String(20),nullable=False),sa.Column("check_in",sa.Time()),sa.Column("check_out",sa.Time()),sa.Column("notes",sa.String(255)),sa.Column("created_at",sa.DateTime(),nullable=False),sa.UniqueConstraint("employee_id","attendance_date",name="uq_hrm_attendance_employee_date")); op.create_index("ix_hrm_attendance_employee_id","hrm_attendance",["employee_id"]); op.create_index("ix_hrm_attendance_attendance_date","hrm_attendance",["attendance_date"])
    op.create_table("hrm_leave_requests",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("employee_id",sa.Integer(),sa.ForeignKey("hrm_employees.id"),nullable=False),sa.Column("leave_type",sa.String(30),nullable=False),sa.Column("start_date",sa.Date(),nullable=False),sa.Column("end_date",sa.Date(),nullable=False),sa.Column("reason",sa.Text()),sa.Column("status",sa.String(20),nullable=False),sa.Column("created_at",sa.DateTime(),nullable=False)); op.create_index("ix_hrm_leave_requests_employee_id","hrm_leave_requests",["employee_id"]); op.create_index("ix_hrm_leave_requests_status","hrm_leave_requests",["status"])
def downgrade():
    op.drop_table("hrm_leave_requests"); op.drop_table("hrm_attendance"); op.drop_table("hrm_employees"); op.drop_table("hrm_users")
